server:
  port: 8761
eureka:
  instance:
#  eureka 实例的主机名
    hostname: eureka-server
  client:
#  不将自己注册在eureka中
    register-with-eureka: false
#  不从eureka上来获取服务的注册信息，因为eureka本身就是注册中心
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:8761/eureka/
